apiVersion: v1
kind: Service
metadata:
  name: dfjsdf3
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "dfjsdf3"
    port: 8080
  selector:
    app: dfjsdf3
